### ISSUE TITLE
Objetivo

### ISSUE THREAD

**Issue by OtacilioN** [OtacilioN/discreta02g02#11]
Pessoal, seguinte: Eu não estou sabendo por onde começar a resolução do problema, acho que pelo fato de eu ter faltado a semana de aula em que o problema foi passado e ter pedido o enunciado, então ele não está muito claro na minha cabeça, tudo que a gente precisa fazer é pegar um número X, ( inclusive eu não estou com o número desse X, se alguém puder postar agradeço), e dizer se ele é primo ou não? Também devo ter faltado a explicação sobre Struct, tô pesquisando aqui sobre mas não tô vendo onde se encaixa no problema, pra ser sincero também não estou entendendo muito, então tipo se alguém puder delegar objetivos específicos do problema poderia ser melhor pra quem está perdido como eu de trabalhar. Alguém pode traçar esses objetivos específicos?

**Comment by OtacilioN** [comment]
Também estou tentando me inspirar no código do grupo 01 mas não tá saindo muita coisa também não, não estou conseguindo entender o propósito de quase nada que existe no código.

**Comment by drbeco** [comment]
`p = 2^64+1 = 18446744073709551617`

Fazer o algoritmo para testar se um dado número `p` qualquer é primo, criando um novo tipo `ullong_t` de 128 bits, com operações bit-a-bit e struct na forma:

```
typedef struct sull
{
    unsigned long h;
    unsigned long l;
} ullong_t;
```

**Comment by OtacilioN** [comment]
Agora eu entendo perfeitamente a importância dos comentários, tô tentando entender a solução do grupo01, alguém sacou como funciona a função "ulet" https://github.com/thaynamorim/discreta02g01/blob/feature-hugo/ex2.c <- Linha 124.

**Comment by OtacilioN** [comment]
if(ulet("6",&x))
        printf("x estourou\n");
    if(ulet("5",&y)) e o melhor, de onde surgiu esse "6" e esse "5" ?

**Comment by vivianesanguinett** [comment]
Ao que parece essa função serve para indicar  se o x vai estourar , ou seja se passa de 64 bits.
