### ISSUE TITLE
Falta arquivo makefile

### ISSUE THREAD

**Issue by OtacilioN** [OtacilioN/discreta02g02#3]
Falta adicionar arquivo makefile em todos os branches.

**Comment by OtacilioN** [comment]
Não adicionei ainda por não ter tanta seguranca ainda com o Git, estarei fazendo o tutorial do SpaceWar, assim que terminado caso alguem nao tenha resolvido ainda posso faze-lo.

**Comment by vivianesanguinett** [comment]
Makefile adcionado.
