### ISSUE TITLE
Duvida - Sobre repositório do esqueleto da programação.

### ISSUE THREAD

**Issue by OtacilioN** [OtacilioN/discreta02g02#8]
Gostaria de saber se o esqueleto da programação "ex2.c" deve ser mantido por hora apenas nos features e no develop, uma vez que ainda não existe nada pronto, ou se ele deve ser colocado já também no release e no master, mesmo que sem nada por hora.

**Comment by drbeco** [comment]
Esqueleto vai desde o feature até o master e fica lá; o master fica esperando novas adições. Mas os features andam rapidamente. Não tem que ficar parado, não. Código, código e mais código nos features; fazendo merge para develop. Assim que se trabalha no esquema gitflow.
